### ISSUE TITLE
Error Response - 401 [Unauthorized]

### ISSUE THREAD

**Issue by alexparker0** [yihong0618/SunoSongsCreator#24]
`{"detail": "Unauthorized"}
Error response <Response [401]>
{"detail": "Unauthorized"}
Error response <Response [401]>
Ignoring exception in command generate:
Traceback (most recent call last):
  File "/home/container/main.py", line 53, in generate
    sg1.save_songs(prompt, "./output", make_instrumental=instrumental, is_custom=False)
  File "/home/container/.local/lib/python3.12/site-packages/suno/suno.py", line 287, in save_songs
    self.get_songs(
  File "/home/container/.local/lib/python3.12/site-packages/suno/suno.py", line 228, in get_songs
    raise Exception(f"Error response {str(response)}")
Exception: Error response <Response [401]>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/container/.local/lib/python3.12/site-packages/discord/commands/core.py", line 131, in wrapped
    ret = await coro(arg)
          ^^^^^^^^^^^^^^^
  File "/home/container/.local/lib/python3.12/site-packages/discord/commands/core.py", line 1013, in _invoke
    await self.callback(ctx, **kwargs)
  File "/home/container/main.py", line 55, in generate
    sg2.save_songs(prompt, "./output", make_instrumental=instrumental, is_custom=False)
  File "/home/container/.local/lib/python3.12/site-packages/suno/suno.py", line 287, in save_songs
    self.get_songs(
  File "/home/container/.local/lib/python3.12/site-packages/suno/suno.py", line 228, in get_songs
    raise Exception(f"Error response {str(response)}")
Exception: Error response <Response [401]>`

The code was working till last week, but it stopped working when I tried it a couple days ago, and I got the same error when I tried it again today. Any help would be appreciated! I have rechecked that the cookie is correct and updated it again, and I'm not getting an error for that as I got before I updated it, so I know that's not the problem, so I can't figure out what it is

**Comment by yihong0618** [comment]
just make a new cookie 
the cookie expire in one week

**Comment by yihong0618** [comment]
pip install -U suno_songs and try again

**Comment by alexparker0** [comment]
I reinstalled it but it's the same thing, it gives one generation, but after that, when I try to run it again, it gives the same 401 error

**Comment by yihong0618** [comment]
your terminal can connect google?

curl google.com

**Comment by alexparker0** [comment]
Yep, I'm pretty sure, since it works very rarely for one song, but then just keeps giving error 401 whenever I send a request

**Comment by yihong0618** [comment]
> Yep, I'm pretty sure, since it works very rarely for one song, but then just keeps giving error 401 whenever I send a request

you need another net...

**Comment by OlegRuban-ai** [comment]
I used IPs from different countries, took cookies from different browsers, but still had the same problem. And until May 4, everything worked fine.

**Comment by alexparker0** [comment]
It's still not working for me as well, I tried all of the solutions and I know the problem isn't my net
